//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""fa986907-81d7-4270-a432-ed7e2e449d2b"",
            ""actions"": [
                {
                    ""name"": ""MouseAction"",
                    ""type"": ""Button"",
                    ""id"": ""f9dec217-547e-48f6-b62e-1af4be74d363"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""57343eba-313c-4cb4-bed8-7f4949b04887"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MouseAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Menu"",
            ""id"": ""119e50f9-5c02-4632-bf91-22e8b1c1ac8b"",
            ""actions"": [
                {
                    ""name"": ""MenuB"",
                    ""type"": ""Button"",
                    ""id"": ""67249632-b4e9-462b-945b-54f0baa18b05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fe9c9247-4546-431f-9926-035c52091e2c"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MenuB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Event"",
            ""id"": ""112b5605-877b-4edf-8bb0-48ba0a12b468"",
            ""actions"": [
                {
                    ""name"": ""ContinueDialogue"",
                    ""type"": ""Button"",
                    ""id"": ""00a2c010-8c7d-43f0-8143-0a8051839822"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChooseOption#1"",
                    ""type"": ""Button"",
                    ""id"": ""7b242c3f-2042-41b8-873d-1647e3ffda6f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChooseOption#2"",
                    ""type"": ""Button"",
                    ""id"": ""113ae382-5287-4b6e-b84b-4451c1dff323"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChooseOption#3"",
                    ""type"": ""Button"",
                    ""id"": ""ccd24e08-13a5-4e86-a1e8-f0fe4d4b6beb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bd58f7c6-e23b-489b-8a67-cce56d032597"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""ContinueDialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""145be3f3-9fbb-4d9a-a09b-81ebbaed3f7b"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""ChooseOption#1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""754952c0-c121-4496-860f-58e76b7d49d4"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""ChooseOption#2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9553cd9-2beb-41b7-ab7c-4f813c94e9c8"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""ChooseOption#3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""General"",
            ""id"": ""1827ea64-68cb-44f4-8e6f-fd2645abfc3c"",
            ""actions"": [
                {
                    ""name"": ""Swap1"",
                    ""type"": ""Button"",
                    ""id"": ""dd2f86b9-af89-46e6-bdbf-42ccbfe84d60"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Swap2"",
                    ""type"": ""Button"",
                    ""id"": ""b9052bc0-d423-43a7-9eff-52e01d147962"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Swap3"",
                    ""type"": ""Button"",
                    ""id"": ""6249782c-a9a3-424a-a329-8348b21e5fc9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateCamera"",
                    ""type"": ""Value"",
                    ""id"": ""4c571a7b-687b-4331-9775-b9a263d23fde"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScrollCamera"",
                    ""type"": ""Value"",
                    ""id"": ""90b711bc-a1ea-4e9f-b9ca-e2a42878da02"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""81daaa77-4f09-4b0e-b552-c9d22339b0d7"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swap1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""834fb2ce-2444-4cbc-82d2-0ddb2300f628"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swap2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3252be42-3c07-4814-af3c-ef223ca6eb97"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swap3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""cda2d2a7-f839-4ff5-9b81-bff9155bd1d4"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""91b47d93-2ff3-4cb3-9d8e-068d92b30743"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""728f0852-23ce-4a33-ae7e-99101d8254c0"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""aeaaaa75-cc97-40bf-9342-8e5e972d135b"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""ScrollCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": []
        }
    ]
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_MouseAction = m_Gameplay.FindAction("MouseAction", throwIfNotFound: true);
        // Menu
        m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
        m_Menu_MenuB = m_Menu.FindAction("MenuB", throwIfNotFound: true);
        // Event
        m_Event = asset.FindActionMap("Event", throwIfNotFound: true);
        m_Event_ContinueDialogue = m_Event.FindAction("ContinueDialogue", throwIfNotFound: true);
        m_Event_ChooseOption1 = m_Event.FindAction("ChooseOption#1", throwIfNotFound: true);
        m_Event_ChooseOption2 = m_Event.FindAction("ChooseOption#2", throwIfNotFound: true);
        m_Event_ChooseOption3 = m_Event.FindAction("ChooseOption#3", throwIfNotFound: true);
        // General
        m_General = asset.FindActionMap("General", throwIfNotFound: true);
        m_General_Swap1 = m_General.FindAction("Swap1", throwIfNotFound: true);
        m_General_Swap2 = m_General.FindAction("Swap2", throwIfNotFound: true);
        m_General_Swap3 = m_General.FindAction("Swap3", throwIfNotFound: true);
        m_General_RotateCamera = m_General.FindAction("RotateCamera", throwIfNotFound: true);
        m_General_ScrollCamera = m_General.FindAction("ScrollCamera", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_MouseAction;
    public struct GameplayActions
    {
        private @PlayerInputs m_Wrapper;
        public GameplayActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseAction => m_Wrapper.m_Gameplay_MouseAction;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @MouseAction.started += instance.OnMouseAction;
            @MouseAction.performed += instance.OnMouseAction;
            @MouseAction.canceled += instance.OnMouseAction;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @MouseAction.started -= instance.OnMouseAction;
            @MouseAction.performed -= instance.OnMouseAction;
            @MouseAction.canceled -= instance.OnMouseAction;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);

    // Menu
    private readonly InputActionMap m_Menu;
    private List<IMenuActions> m_MenuActionsCallbackInterfaces = new List<IMenuActions>();
    private readonly InputAction m_Menu_MenuB;
    public struct MenuActions
    {
        private @PlayerInputs m_Wrapper;
        public MenuActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @MenuB => m_Wrapper.m_Menu_MenuB;
        public InputActionMap Get() { return m_Wrapper.m_Menu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
        public void AddCallbacks(IMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuActionsCallbackInterfaces.Add(instance);
            @MenuB.started += instance.OnMenuB;
            @MenuB.performed += instance.OnMenuB;
            @MenuB.canceled += instance.OnMenuB;
        }

        private void UnregisterCallbacks(IMenuActions instance)
        {
            @MenuB.started -= instance.OnMenuB;
            @MenuB.performed -= instance.OnMenuB;
            @MenuB.canceled -= instance.OnMenuB;
        }

        public void RemoveCallbacks(IMenuActions instance)
        {
            if (m_Wrapper.m_MenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuActions @Menu => new MenuActions(this);

    // Event
    private readonly InputActionMap m_Event;
    private List<IEventActions> m_EventActionsCallbackInterfaces = new List<IEventActions>();
    private readonly InputAction m_Event_ContinueDialogue;
    private readonly InputAction m_Event_ChooseOption1;
    private readonly InputAction m_Event_ChooseOption2;
    private readonly InputAction m_Event_ChooseOption3;
    public struct EventActions
    {
        private @PlayerInputs m_Wrapper;
        public EventActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @ContinueDialogue => m_Wrapper.m_Event_ContinueDialogue;
        public InputAction @ChooseOption1 => m_Wrapper.m_Event_ChooseOption1;
        public InputAction @ChooseOption2 => m_Wrapper.m_Event_ChooseOption2;
        public InputAction @ChooseOption3 => m_Wrapper.m_Event_ChooseOption3;
        public InputActionMap Get() { return m_Wrapper.m_Event; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EventActions set) { return set.Get(); }
        public void AddCallbacks(IEventActions instance)
        {
            if (instance == null || m_Wrapper.m_EventActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_EventActionsCallbackInterfaces.Add(instance);
            @ContinueDialogue.started += instance.OnContinueDialogue;
            @ContinueDialogue.performed += instance.OnContinueDialogue;
            @ContinueDialogue.canceled += instance.OnContinueDialogue;
            @ChooseOption1.started += instance.OnChooseOption1;
            @ChooseOption1.performed += instance.OnChooseOption1;
            @ChooseOption1.canceled += instance.OnChooseOption1;
            @ChooseOption2.started += instance.OnChooseOption2;
            @ChooseOption2.performed += instance.OnChooseOption2;
            @ChooseOption2.canceled += instance.OnChooseOption2;
            @ChooseOption3.started += instance.OnChooseOption3;
            @ChooseOption3.performed += instance.OnChooseOption3;
            @ChooseOption3.canceled += instance.OnChooseOption3;
        }

        private void UnregisterCallbacks(IEventActions instance)
        {
            @ContinueDialogue.started -= instance.OnContinueDialogue;
            @ContinueDialogue.performed -= instance.OnContinueDialogue;
            @ContinueDialogue.canceled -= instance.OnContinueDialogue;
            @ChooseOption1.started -= instance.OnChooseOption1;
            @ChooseOption1.performed -= instance.OnChooseOption1;
            @ChooseOption1.canceled -= instance.OnChooseOption1;
            @ChooseOption2.started -= instance.OnChooseOption2;
            @ChooseOption2.performed -= instance.OnChooseOption2;
            @ChooseOption2.canceled -= instance.OnChooseOption2;
            @ChooseOption3.started -= instance.OnChooseOption3;
            @ChooseOption3.performed -= instance.OnChooseOption3;
            @ChooseOption3.canceled -= instance.OnChooseOption3;
        }

        public void RemoveCallbacks(IEventActions instance)
        {
            if (m_Wrapper.m_EventActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IEventActions instance)
        {
            foreach (var item in m_Wrapper.m_EventActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_EventActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public EventActions @Event => new EventActions(this);

    // General
    private readonly InputActionMap m_General;
    private List<IGeneralActions> m_GeneralActionsCallbackInterfaces = new List<IGeneralActions>();
    private readonly InputAction m_General_Swap1;
    private readonly InputAction m_General_Swap2;
    private readonly InputAction m_General_Swap3;
    private readonly InputAction m_General_RotateCamera;
    private readonly InputAction m_General_ScrollCamera;
    public struct GeneralActions
    {
        private @PlayerInputs m_Wrapper;
        public GeneralActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Swap1 => m_Wrapper.m_General_Swap1;
        public InputAction @Swap2 => m_Wrapper.m_General_Swap2;
        public InputAction @Swap3 => m_Wrapper.m_General_Swap3;
        public InputAction @RotateCamera => m_Wrapper.m_General_RotateCamera;
        public InputAction @ScrollCamera => m_Wrapper.m_General_ScrollCamera;
        public InputActionMap Get() { return m_Wrapper.m_General; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GeneralActions set) { return set.Get(); }
        public void AddCallbacks(IGeneralActions instance)
        {
            if (instance == null || m_Wrapper.m_GeneralActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GeneralActionsCallbackInterfaces.Add(instance);
            @Swap1.started += instance.OnSwap1;
            @Swap1.performed += instance.OnSwap1;
            @Swap1.canceled += instance.OnSwap1;
            @Swap2.started += instance.OnSwap2;
            @Swap2.performed += instance.OnSwap2;
            @Swap2.canceled += instance.OnSwap2;
            @Swap3.started += instance.OnSwap3;
            @Swap3.performed += instance.OnSwap3;
            @Swap3.canceled += instance.OnSwap3;
            @RotateCamera.started += instance.OnRotateCamera;
            @RotateCamera.performed += instance.OnRotateCamera;
            @RotateCamera.canceled += instance.OnRotateCamera;
            @ScrollCamera.started += instance.OnScrollCamera;
            @ScrollCamera.performed += instance.OnScrollCamera;
            @ScrollCamera.canceled += instance.OnScrollCamera;
        }

        private void UnregisterCallbacks(IGeneralActions instance)
        {
            @Swap1.started -= instance.OnSwap1;
            @Swap1.performed -= instance.OnSwap1;
            @Swap1.canceled -= instance.OnSwap1;
            @Swap2.started -= instance.OnSwap2;
            @Swap2.performed -= instance.OnSwap2;
            @Swap2.canceled -= instance.OnSwap2;
            @Swap3.started -= instance.OnSwap3;
            @Swap3.performed -= instance.OnSwap3;
            @Swap3.canceled -= instance.OnSwap3;
            @RotateCamera.started -= instance.OnRotateCamera;
            @RotateCamera.performed -= instance.OnRotateCamera;
            @RotateCamera.canceled -= instance.OnRotateCamera;
            @ScrollCamera.started -= instance.OnScrollCamera;
            @ScrollCamera.performed -= instance.OnScrollCamera;
            @ScrollCamera.canceled -= instance.OnScrollCamera;
        }

        public void RemoveCallbacks(IGeneralActions instance)
        {
            if (m_Wrapper.m_GeneralActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGeneralActions instance)
        {
            foreach (var item in m_Wrapper.m_GeneralActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GeneralActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GeneralActions @General => new GeneralActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IGameplayActions
    {
        void OnMouseAction(InputAction.CallbackContext context);
    }
    public interface IMenuActions
    {
        void OnMenuB(InputAction.CallbackContext context);
    }
    public interface IEventActions
    {
        void OnContinueDialogue(InputAction.CallbackContext context);
        void OnChooseOption1(InputAction.CallbackContext context);
        void OnChooseOption2(InputAction.CallbackContext context);
        void OnChooseOption3(InputAction.CallbackContext context);
    }
    public interface IGeneralActions
    {
        void OnSwap1(InputAction.CallbackContext context);
        void OnSwap2(InputAction.CallbackContext context);
        void OnSwap3(InputAction.CallbackContext context);
        void OnRotateCamera(InputAction.CallbackContext context);
        void OnScrollCamera(InputAction.CallbackContext context);
    }
}
